name: Github Pages Deploy
on:
  push:
    branches:
      - main
jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Unit Test
        run: npm test

      - name: Build
        run: npm run build

      - name: e2e Test
        run: npm run e2e

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./dist
